import { test, expect } from '@playwright/test';

test.describe('Export Excel Flow', () => {
  // Auth: global storageState (auth/admin.json) applied via playwright.config.ts L34+L56.
  // ShopERP uses Cookie auth via /dev/login — no login form exists.

  test('should export revenue report to Excel', async ({ page }) => {
    const from = '2026-01-01';
    const to = '2026-12-31';
    const response = await page.request.get(`/api/reports/export/excel?type=revenue&from=${from}&to=${to}`);

    expect(response.status()).toBe(200);
    expect(response.headers()['content-type']).toBe('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    expect(response.headers()['content-disposition']).toContain('revenue-report');

    const body = await response.body();
    expect(body.length).toBeGreaterThan(0);
    expect(body.toString('hex', 0, 4)).toBe('504b0304'); // OOXML ZIP magic number
  });

  test('should export inventory report to Excel', async ({ page }) => {
    const response = await page.request.get('/api/reports/export/excel?type=inventory');

    expect(response.status()).toBe(200);
    expect(response.headers()['content-type']).toBe('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    expect(response.headers()['content-disposition']).toContain('inventory-report');

    const body = await response.body();
    expect(body.length).toBeGreaterThan(0);
  });

  // SaaS W3: Staff auth file (auth/staff.json) now generated by global-setup.
  test.describe('Staff role — unauthorized export', () => {
    test.use({ storageState: 'auth/staff.json' });

    test('should reject export for unauthorized role', async ({ page }) => {
      const response = await page.request.get('/api/reports/export/excel?type=revenue');
      expect(response.status()).toBe(403);
    });
  });
});
