import { test, expect } from '@playwright/test';
import { loadEnvConfig, isTierEnabled } from '../utils/env-config';

// Bug 2A — Accounting menu visibility by tenant type (Phase 1)
// Verifies that "Sổ HKD (TT 152)" menu is only shown for HKD tenants,
// and "Báo Cáo Tài Chính" is only shown for Enterprise/Company tenants.
//
// Test environment uses a single HKD tenant (auth/admin.json = Owner of HKD tenant).
// The Company tenant case is noted as a manual verification item (requires a second
// tenant auth file which the current global-setup does not generate).

const config = loadEnvConfig();

test.describe.configure({ mode: isTierEnabled('e2e') ? 'parallel' : 'skip' });

test.describe('Bug 2A — Accounting menu visibility by tenant type', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(`${config.SHOPERP_URL}/accounting`);
    await page.waitForLoadState('networkidle');
  });

  // ── HKD tenant (default test tenant) ──────────────────────────────────────

  test('HKD tenant sees "Sổ HKD" menu item', async ({ page }) => {
    // Navigate to accounting page — AccountingLayout renders sidebar nav
    await expect(page).toHaveURL(/\/accounting/);

    // "Sổ HKD (TT 152)" nav link should be visible for HKD tenant
    const hkdMenuLink = page.locator('nav a[href="/accounting/hkd-books"]');
    await expect(hkdMenuLink).toBeVisible();
  });

  test('HKD tenant does NOT see "Báo Cáo Tài Chính" menu item', async ({ page }) => {
    await expect(page).toHaveURL(/\/accounting/);

    // "Báo Cáo Tài Chính" nav link should NOT exist for HKD tenant
    const vasMenuLink = page.locator('nav a[href="/accounting/financial-reports"]');
    await expect(vasMenuLink).toHaveCount(0);
  });

  // ── Company tenant (manual verification) ──────────────────────────────────
  // NOTE: The current E2E test environment uses a single HKD tenant.
  // To test the Company tenant case, a second auth file (auth/enterprise.json)
  // would need to be generated by global-setup for an Enterprise/Company tenant.
  // Manual verification: log in as Company tenant Owner → verify "Báo Cáo Tài Chính"
  // is visible and "Sổ HKD (TT 152)" is NOT visible in the accounting sidebar.
});
