import { test, expect } from '@playwright/test';
import { loadEnvConfig, isTierEnabled } from '../utils/env-config';

// Wave 4 — RBAC Enforcement E2E Tests [W4-T6]
// Verifies that role policies are enforced at the Blazor UI layer:
//   - Staff cannot access Owner-only pages → redirected to /access-denied
//   - Owner can access all pages
//   - Guard is redirected to Guard/Scan after login
//
// SaaS W3 — Multi-role auth files now generated by global-setup:
//   - auth/admin.json       → Owner       (full access)
//   - auth/staff.json       → Staff       (order management)
//   - auth/storekeeper.json → StoreKeeper (inventory)
//   - auth/guard.json       → Guard       (check-in/out)
//   Each multi-role test block uses test.use({ storageState: 'auth/<role>.json' }).
//   Unauthenticated test overrides storageState to empty (no cookies).

const config = loadEnvConfig();

test.describe.configure({ mode: isTierEnabled('e2e') ? 'parallel' : 'skip' });

test.describe('RBAC Enforcement — Blazor UI Layer', () => {

  // ── Owner tests — use global storageState (auth/admin.json = Owner role) ──

  // ── Test: Owner can access Accounting page ──────────────────────────────
  test('Owner login → can access /accounting dashboard', async ({ page }) => {
    await page.goto(`${config.SHOPERP_URL}/accounting`);
    await page.waitForLoadState('networkidle');

    // Should remain on accounting page (not redirected)
    expect(page.url()).toContain('/accounting');
    expect(page.url()).not.toContain('/access-denied');

    // Verify accounting dashboard content is visible
    const heading = page.getByRole('heading', { name: /Kế Toán Dashboard/i });
    await expect(heading).toBeVisible();
  });

  // ── Test: NavMenu shows accounting items for Owner ─────────────────────
  test('NavMenu shows Accounting links for Owner role', async ({ page }) => {
    await page.goto(`${config.SHOPERP_URL}/`);
    await page.waitForLoadState('networkidle');

    // Accounting nav link SHOULD be visible
    const accountingLink = page.locator('nav a[href="accounting"]');
    await expect(accountingLink).toBeVisible();
  });

  // ── Staff tests — use auth/staff.json ──────────────────────────────────
  test.describe('Staff role', () => {
    test.use({ storageState: 'auth/staff.json' });

    test('Staff cannot access /accounting → redirected to access-denied', async ({ page }) => {
      await page.goto(`${config.SHOPERP_URL}/accounting`);
      await page.waitForLoadState('networkidle');

      // Staff should be denied access to accounting
      expect(page.url()).toContain('/access-denied');
    });

    test('Staff cannot access /accounting/period-closing', async ({ page }) => {
      await page.goto(`${config.SHOPERP_URL}/accounting/period-closing`);
      await page.waitForLoadState('networkidle');

      expect(page.url()).toContain('/access-denied');
    });

    test('NavMenu does not show Accounting links for Staff role', async ({ page }) => {
      await page.goto(`${config.SHOPERP_URL}/`);
      await page.waitForLoadState('networkidle');

      const accountingLink = page.locator('nav a[href="accounting"]');
      await expect(accountingLink).toHaveCount(0);
    });
  });

  // ── StoreKeeper tests — use auth/storekeeper.json ──────────────────────
  test.describe('StoreKeeper role', () => {
    test.use({ storageState: 'auth/storekeeper.json' });

    test('StoreKeeper can access /einvoice dashboard', async ({ page }) => {
      await page.goto(`${config.SHOPERP_URL}/einvoice`);
      await page.waitForLoadState('networkidle');

      // StoreKeeper should be able to access eInvoice dashboard
      expect(page.url()).not.toContain('/access-denied');
    });

    test('StoreKeeper cannot access /einvoice/configuration (Owner only)', async ({ page }) => {
      await page.goto(`${config.SHOPERP_URL}/einvoice/configuration`);
      await page.waitForLoadState('networkidle');

      expect(page.url()).toContain('/access-denied');
    });
  });

  // ── Guard tests — use auth/guard.json ──────────────────────────────────
  test.describe('Guard role', () => {
    test.use({ storageState: 'auth/guard.json' });

    test('Guard cannot access /accounting → redirected to access-denied', async ({ page }) => {
      await page.goto(`${config.SHOPERP_URL}/accounting`);
      await page.waitForLoadState('networkidle');

      expect(page.url()).toContain('/access-denied');
    });
  });

  // ── Unauthenticated test — override storageState to empty (no session) ──
  test.describe('Unauthenticated access', () => {
    test.use({ storageState: { cookies: [], origins: [] } });

    test('Unauthenticated access to /accounting → redirect to Login', async ({ page }) => {
      // Navigate without any auth session
      await page.goto(`${config.SHOPERP_URL}/accounting`);
      await page.waitForLoadState('networkidle');

      // Should be redirected to Login page
      expect(page.url()).toContain('/Login');
    });
  });

});
