import { test, expect } from '@playwright/test';
import { loadEnvConfig, isTierEnabled } from '../utils/env-config';

// Wave 4 — RBAC Enforcement E2E Tests [W4-T6]
// Verifies that role policies are enforced at the Blazor UI layer:
//   - Staff cannot access Owner-only pages → redirected to /access-denied
//   - Owner can access all pages
//   - Guard is redirected to Guard/Scan after login
//
// Wave 2 (E2E Cleanup Pattern D) — Auth fix:
//   - Owner tests use global storageState (auth/admin.json = Owner role, applied via playwright.config.ts L34+L56).
//   - Multi-role tests (Staff/StoreKeeper/Guard) are SKIPPED — global-setup only generates auth/admin.json.
//     To enable them, generate auth/staff.json, auth/storekeeper.json, auth/guard.json via a separate
//     multi-role auth setup task (out of Wave 2 scope). Then replace test.skip with
//     test.use({ storageState: 'auth/<role>.json' }) per test.describe block.
//   - Unauthenticated test overrides storageState to empty (no cookies).

const config = loadEnvConfig();

test.describe.configure({ mode: isTierEnabled('e2e') ? 'parallel' : 'skip' });

test.describe('RBAC Enforcement — Blazor UI Layer', () => {

  // ── Owner tests — use global storageState (auth/admin.json = Owner role) ──

  // ── Test: Owner can access Accounting page ──────────────────────────────
  test('Owner login → can access /accounting dashboard', async ({ page }) => {
    await page.goto(`${config.SHOPERP_URL}/accounting`);
    await page.waitForLoadState('networkidle');

    // Should remain on accounting page (not redirected)
    expect(page.url()).toContain('/accounting');
    expect(page.url()).not.toContain('/access-denied');

    // Verify accounting dashboard content is visible
    const heading = page.getByRole('heading', { name: /Kế Toán Dashboard/i });
    await expect(heading).toBeVisible();
  });

  // ── Test: NavMenu shows accounting items for Owner ─────────────────────
  test('NavMenu shows Accounting links for Owner role', async ({ page }) => {
    await page.goto(`${config.SHOPERP_URL}/`);
    await page.waitForLoadState('networkidle');

    // Accounting nav link SHOULD be visible
    const accountingLink = page.locator('nav a[href="accounting"]');
    await expect(accountingLink).toBeVisible();
  });

  // ── Multi-role tests — SKIPPED (need auth/<role>.json, not generated by global-setup) ──

  test('Staff login → redirected to KDS, cannot access /accounting', async () => {
    test.skip(true, 'Requires auth/staff.json — not generated by global-setup. See Wave 2 task card.');
  });

  test('Staff cannot access /accounting/period-closing', async () => {
    test.skip(true, 'Requires auth/staff.json — not generated by global-setup. See Wave 2 task card.');
  });

  test('StoreKeeper can access /einvoice dashboard', async () => {
    test.skip(true, 'Requires auth/storekeeper.json — not generated by global-setup. See Wave 2 task card.');
  });

  test('StoreKeeper cannot access /einvoice/configuration (Owner only)', async () => {
    test.skip(true, 'Requires auth/storekeeper.json — not generated by global-setup. See Wave 2 task card.');
  });

  test('Guard login → redirected to /guard/scan', async () => {
    test.skip(true, 'Requires auth/guard.json — not generated by global-setup. See Wave 2 task card.');
  });

  test('NavMenu does not show Accounting links for Staff role', async () => {
    test.skip(true, 'Requires auth/staff.json — not generated by global-setup. See Wave 2 task card.');
  });

  // ── Unauthenticated test — override storageState to empty (no session) ──
  test.describe('Unauthenticated access', () => {
    test.use({ storageState: { cookies: [], origins: [] } });

    test('Unauthenticated access to /accounting → redirect to Login', async ({ page }) => {
      // Navigate without any auth session
      await page.goto(`${config.SHOPERP_URL}/accounting`);
      await page.waitForLoadState('networkidle');

      // Should be redirected to Login page
      expect(page.url()).toContain('/Login');
    });
  });

});
