import json, sys
data = sys.stdin.buffer.read().decode("utf-8-sig")
m = json.loads(data)
print("name:", m.get("name"))
print("short_name:", m.get("short_name"))
print("start_url:", m.get("start_url"))
print("display:", m.get("display"))
print("id:", m.get("id"))
print("scope:", m.get("scope"))
print("icons_count:", len(m.get("icons", [])))
print("has_192:", any(i.get("sizes") == "192x192" for i in m.get("icons", [])))
print("has_512:", any(i.get("sizes") == "512x512" for i in m.get("icons", [])))
print("has_maskable_192:", any(i.get("sizes") == "192x192" and "maskable" in i.get("purpose", "") for i in m.get("icons", [])))
print("has_maskable_512:", any(i.get("sizes") == "512x512" and "maskable" in i.get("purpose", "") for i in m.get("icons", [])))
print("display_override:", m.get("display_override"))
print("prefer_related:", m.get("prefer_related_applications"))
print("screenshots:", len(m.get("screenshots", [])))
print("launch_handler:", m.get("launch_handler"))
print("categories:", m.get("categories"))
