using VanAn.Shared.Domain.Common;

namespace VanAn.Shared.Domain.Aggregates.TenantAggregate
{
    /// <summary>
    /// GTM Drill Machine W2 (2026-09-08, D3): Registration record for merchant mới chưa có tenant.
    /// Merchant từ demo (/demo) hoặc audit (/kiem-tra-cua-hang) submit registration → SysAdmin queue
    /// → admin manually creates tenant via existing Crawl-to-Onboard pipeline.
    ///
    /// Audit-type entity (precedent CrawlSource): inherits BaseEntity directly (not AggregateRoot —
    /// no domain events for MVP; admin queue notification via polling, not event-driven).
    ///
    /// NOT tenant-scoped: TenantId = Guid.Empty sentinel (merchant chưa thuộc tenant nào).
    /// Excluded from multi-tenancy query filter in VanAnDbContext.ApplyMultiTenancyFilters
    /// (like KhachLinkInstance, TenantDomain — platform-level entities).
    ///
    /// Single-Identity Pattern: Id = PK (Guid). No business key VO. Constructor uses BaseEntity()
    /// parameterless — Id auto-generated by BaseEntity (Guid.NewGuid()).
    /// </summary>
    public class TenantRegistration : BaseEntity
    {
        /// <summary>Registration status lifecycle.</summary>
        public enum RegistrationStatus
        {
            Submitted = 0,
            Contacted = 1,
            Onboarded = 2,
            Rejected = 3
        }

        // ── Merchant info (from demo prefill or direct form) ────────────────
        public string ShopName { get; private set; } = string.Empty;
        public string? Industry { get; private set; }
        public string? LogoUrl { get; private set; }

        // ── Contact info (from Register form) ───────────────────────────────
        public string ContactName { get; private set; } = string.Empty;
        public string ContactPhone { get; private set; } = string.Empty;
        public string? ContactEmail { get; private set; }

        // ── Source tracking ──────────────────────────────────────────────────
        public string Source { get; private set; } = string.Empty; // "demo" | "audit" | "direct"

        // ── Anti-bot verification ────────────────────────────────────────────
        public bool TurnstileVerified { get; private set; }

        // ── Lifecycle ─────────────────────────────────────────────────────────
        public RegistrationStatus Status { get; private set; } = RegistrationStatus.Submitted;
        public DateTime SubmittedAt { get; private set; }

        // ── Review (set by SysAdmin) ──────────────────────────────────────────
        public Guid? ReviewedByUserId { get; private set; }
        public DateTime? ReviewedAt { get; private set; }
        public string? RejectionReason { get; private set; }

        // ── Onboarding result (set when admin creates tenant from this registration) ──
        public Guid? OnboardedTenantId { get; private set; }

        // EF Core requires parameterless constructor
        private TenantRegistration() { }

        /// <summary>
        /// Factory: create a new TenantRegistration submitted by merchant via Register form.
        /// </summary>
        /// <param name="shopName">Shop/business name (from demo prefill or direct input).</param>
        /// <param name="contactName">Contact person name (required).</param>
        /// <param name="contactPhone">Contact phone (required — admin uses for follow-up).</param>
        /// <param name="source">Registration source: "demo", "audit", or "direct".</param>
        /// <param name="turnstileVerified">Whether Cloudflare Turnstile verification passed server-side.</param>
        /// <param name="industry">Optional industry/category from demo.</param>
        /// <param name="logoUrl">Optional logo URL from demo upload.</param>
        /// <param name="contactEmail">Optional contact email.</param>
        public static TenantRegistration Create(
            string shopName,
            string contactName,
            string contactPhone,
            string source,
            bool turnstileVerified,
            string? industry = null,
            string? logoUrl = null,
            string? contactEmail = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(shopName);
            ArgumentException.ThrowIfNullOrWhiteSpace(contactName);
            ArgumentException.ThrowIfNullOrWhiteSpace(contactPhone);
            ArgumentException.ThrowIfNullOrWhiteSpace(source);

            var registration = new TenantRegistration
            {
                ShopName = shopName,
                ContactName = contactName,
                ContactPhone = contactPhone,
                Source = source,
                TurnstileVerified = turnstileVerified,
                Industry = industry,
                LogoUrl = logoUrl,
                ContactEmail = contactEmail,
                Status = RegistrationStatus.Submitted,
                SubmittedAt = DateTime.UtcNow
            };
            // TenantId = Guid.Empty sentinel — merchant chưa thuộc tenant nào.
            // BaseEntity parameterless constructor sets TenantId = null! — set explicitly to Empty.
            registration.SetTenantId(new TenantId(Guid.Empty));
            return registration;
        }

        /// <summary>
        /// SysAdmin marks registration as Contacted (follow-up initiated).
        /// Transitions Status → Contacted.
        /// </summary>
        public void MarkContacted(Guid reviewedByUserId)
        {
            if (Status != RegistrationStatus.Submitted)
                throw new InvalidOperationException($"Cannot mark as contacted in status {Status}. Only Submitted registrations can be contacted.");

            if (reviewedByUserId == Guid.Empty)
                throw new ArgumentException("ReviewedByUserId cannot be empty.", nameof(reviewedByUserId));

            Status = RegistrationStatus.Contacted;
            ReviewedByUserId = reviewedByUserId;
            ReviewedAt = DateTime.UtcNow;
            UpdateAudit();
        }

        /// <summary>
        /// SysAdmin marks registration as Onboarded — tenant created from this registration.
        /// Transitions Status → Onboarded. Records the new tenant ID for traceability.
        /// </summary>
        public void MarkOnboarded(Guid reviewedByUserId, Guid onboardedTenantId)
        {
            if (Status != RegistrationStatus.Submitted && Status != RegistrationStatus.Contacted)
                throw new InvalidOperationException($"Cannot mark as onboarded in status {Status}. Only Submitted or Contacted registrations can be onboarded.");

            if (reviewedByUserId == Guid.Empty)
                throw new ArgumentException("ReviewedByUserId cannot be empty.", nameof(reviewedByUserId));

            if (onboardedTenantId == Guid.Empty)
                throw new ArgumentException("OnboardedTenantId cannot be empty.", nameof(onboardedTenantId));

            Status = RegistrationStatus.Onboarded;
            ReviewedByUserId = reviewedByUserId;
            ReviewedAt = DateTime.UtcNow;
            OnboardedTenantId = onboardedTenantId;
            UpdateAudit();
        }

        /// <summary>
        /// SysAdmin rejects the registration with reason.
        /// </summary>
        public void Reject(Guid reviewedByUserId, string reason)
        {
            if (Status == RegistrationStatus.Onboarded || Status == RegistrationStatus.Rejected)
                throw new InvalidOperationException($"Cannot reject in status {Status}.");

            if (reviewedByUserId == Guid.Empty)
                throw new ArgumentException("ReviewedByUserId cannot be empty.", nameof(reviewedByUserId));

            ArgumentException.ThrowIfNullOrWhiteSpace(reason);

            Status = RegistrationStatus.Rejected;
            ReviewedByUserId = reviewedByUserId;
            ReviewedAt = DateTime.UtcNow;
            RejectionReason = reason;
            UpdateAudit();
        }

        // ── Query helpers ─────────────────────────────────────────────────────
        public bool IsSubmitted() => Status == RegistrationStatus.Submitted;
        public bool IsContacted() => Status == RegistrationStatus.Contacted;
        public bool IsOnboarded() => Status == RegistrationStatus.Onboarded;
        public bool IsRejected() => Status == RegistrationStatus.Rejected;
    }
}
