using VanAn.Shared.Domain.Common;

namespace VanAn.Shared.Domain.Aggregates.TenantAggregate
{
    /// <summary>
    /// Crawl-to-Onboard Pipeline (2026-08-25): Claim request submitted by business owner
    /// for a Pending tenant. Goes to SysAdmin queue for review (Approve → Verify, or Reject).
    ///
    /// Single-Identity Pattern (correction C1): FK to Tenants is via BaseEntity.TenantId
    /// (TenantId value object — after refactor, TenantId.Value == Tenants.Id PK).
    /// No separate Guid TenantId property — BaseEntity.TenantId IS the FK.
    ///
    /// Aggregate root: has its own lifecycle (Submitted → Approved/Rejected) + domain events.
    /// </summary>
    public class TenantClaimRequest : AggregateRoot
    {
        /// <summary>Claim status lifecycle.</summary>
        public enum ClaimStatus
        {
            Submitted = 0,
            Approved = 1,
            Rejected = 2
        }

        // ── Claimant info (submitted by business owner via Claim form) ────────
        public string ClaimantName { get; private set; } = string.Empty;
        public string ClaimantPhone { get; private set; } = string.Empty;
        public string? ClaimantEmail { get; private set; }
        public string GpkdImageUrl { get; private set; } = string.Empty;
        public string TaxCodeSubmitted { get; private set; } = string.Empty;

        // ── Lifecycle ─────────────────────────────────────────────────────────
        public ClaimStatus Status { get; private set; } = ClaimStatus.Submitted;
        public DateTime SubmittedAt { get; private set; }

        // ── Review (set by SysAdmin) ──────────────────────────────────────────
        public Guid? ReviewedByUserId { get; private set; }
        public DateTime? ReviewedAt { get; private set; }
        public string? RejectionReason { get; private set; }

        // EF Core requires parameterless constructor
        private TenantClaimRequest() { }

        /// <summary>
        /// Factory: create a new Claim request submitted by business owner.
        /// Raises TenantClaimRequestedEvent for SysAdmin queue notification.
        /// </summary>
        /// <param name="tenantId">The Pending tenant being claimed (FK to Tenants.Id via BaseEntity.TenantId).</param>
        /// <param name="claimantName">Owner name (from Claim form).</param>
        /// <param name="claimantPhone">Owner phone (from Claim form — consented per M3).</param>
        /// <param name="gpkdImageUrl">URL to uploaded GPKD image (Cloudinary).</param>
        /// <param name="taxCodeSubmitted">Tax code entered by claimant (cross-checked vs Settings.TaxCode).</param>
        /// <param name="claimantEmail">Optional email for notifications.</param>
        public static TenantClaimRequest Create(
            TenantId tenantId,
            string claimantName,
            string claimantPhone,
            string gpkdImageUrl,
            string taxCodeSubmitted,
            string? claimantEmail = null)
        {
            ArgumentException.ThrowIfNullOrWhiteSpace(claimantName);
            ArgumentException.ThrowIfNullOrWhiteSpace(claimantPhone);
            ArgumentException.ThrowIfNullOrWhiteSpace(gpkdImageUrl);
            ArgumentException.ThrowIfNullOrWhiteSpace(taxCodeSubmitted);

            var request = new TenantClaimRequest
            {
                ClaimantName = claimantName,
                ClaimantPhone = claimantPhone,
                ClaimantEmail = claimantEmail,
                GpkdImageUrl = gpkdImageUrl,
                TaxCodeSubmitted = taxCodeSubmitted,
                Status = ClaimStatus.Submitted,
                SubmittedAt = DateTime.UtcNow
            };
            request.SetTenantId(tenantId);  // BaseEntity.TenantId — FK to Tenants.Id
            // Note: Id is auto-generated by BaseEntity (Guid.NewGuid()) —
            // service layer may override via EF Core Entry API if needed (UUIDv7)
            request.AddDomainEvent(new TenantClaimRequestedEvent(
                tenantId.Value, request.Id, claimantName, DateTime.UtcNow));
            return request;
        }

        /// <summary>
        /// SysAdmin approves the claim. Transitions Status → Approved.
        /// Caller is responsible for also calling Tenant.Verify() + creating owner user.
        /// Raises TenantClaimApprovedEvent (with OwnerUserId from Verify step).
        /// </summary>
        public void Approve(Guid reviewedByUserId, Guid ownerUserId)
        {
            if (Status != ClaimStatus.Submitted)
                throw new InvalidOperationException($"Cannot approve claim in status {Status}. Only Submitted claims can be approved.");
            if (reviewedByUserId == Guid.Empty)
                throw new ArgumentException("ReviewedByUserId cannot be empty.", nameof(reviewedByUserId));
            if (ownerUserId == Guid.Empty)
                throw new ArgumentException("OwnerUserId cannot be empty.", nameof(ownerUserId));

            Status = ClaimStatus.Approved;
            ReviewedByUserId = reviewedByUserId;
            ReviewedAt = DateTime.UtcNow;
            UpdateAudit();
            AddDomainEvent(new TenantClaimApprovedEvent(
                TenantId.Value, Id, ownerUserId, reviewedByUserId, DateTime.UtcNow));
        }

        /// <summary>
        /// SysAdmin rejects the claim. Transitions Status → Rejected with reason.
        /// </summary>
        public void Reject(Guid reviewedByUserId, string reason)
        {
            if (Status != ClaimStatus.Submitted)
                throw new InvalidOperationException($"Cannot reject claim in status {Status}. Only Submitted claims can be rejected.");
            if (reviewedByUserId == Guid.Empty)
                throw new ArgumentException("ReviewedByUserId cannot be empty.", nameof(reviewedByUserId));
            ArgumentException.ThrowIfNullOrWhiteSpace(reason);

            Status = ClaimStatus.Rejected;
            ReviewedByUserId = reviewedByUserId;
            ReviewedAt = DateTime.UtcNow;
            RejectionReason = reason;
            UpdateAudit();
        }

        // ── Query helpers ─────────────────────────────────────────────────────
        public bool IsSubmitted() => Status == ClaimStatus.Submitted;
        public bool IsApproved() => Status == ClaimStatus.Approved;
        public bool IsRejected() => Status == ClaimStatus.Rejected;
    }
}
