using VanAn.Shared.Domain;

namespace VanAn.CoreHub.Services.Data;

/// <summary>
/// TT 71/2024/TT-BTC report templates — VERIFIED from Phụ lục IV (Biểu mẫu BCTC năm của HTX).
/// Source: docs/AI/tasks/tt71_htx_accounting/spec/tt71-pl-i-ii-iv.txt (MỤC I — BIỂU MẪU BÁO CÁO).
///   B01-HTX: Báo cáo tình hình tài chính
///   B02-HTX: Báo cáo kết quả hoạt động (tách giao dịch nội bộ/ngoài)
///   B09-HTX: Bản thuyết minh BCTC (text structure — generated by FinancialStatementNotesService)
/// Reuses the generic Tt99ReportTemplate/Tt99TemplateLine records (Mã số → account mapping structure).
/// NOTE: TT 71 KHÔNG yêu cầu B03 (Báo cáo lưu chuyển tiền tệ) — UI ẩn tab cho tenant HTX.
/// </summary>
public static class Tt71Templates
{
    // ════════════════════════════════════════════════════════════════════════════
    // B01-HTX: Báo cáo tình hình tài chính (VERIFIED from Phụ lục IV TT 71 — Mục I.1)
    // ════════════════════════════════════════════════════════════════════════════
    public static Tt99ReportTemplate BalanceSheetTt71 => new(
        AccountingStandard.TT71_2024, "B01-HTX",
        new List<Tt99TemplateLine>
        {
            // TÀI SẢN
            new("110", "1. Tiền", 1, new[]{"111","112"}, false, false),
            new("120", "2. Đầu tư tài chính", 1, new[]{"121"}, false, false),
            // Mã 130 theo spec gồm số dư Nợ chi tiết của 131/132/136/138/141/334/338 + Nợ chi tiết 331.
            // Hệ thống không tách số dư theo bên chi tiết → dùng nhóm phải thu chính (131/132/136/138/141/338);
            // 331/334 (phải trả, normal credit) nằm ở Nợ phải trả — tránh double-count.
            new("130", "3. Các khoản phải thu", 1, new[]{"131","132","136","138","141","338"}, false, false),
            new("137", "Trong đó: Phải thu từ hoạt động cho vay nội bộ", 2, new[]{"132"}, false, false),
            new("140", "4. Hàng tồn kho", 1, new[]{"151","152","154","156","157"}, false, false),
            new("150", "5. Tài sản cố định", 1, Array.Empty<string>(), true, false),
            new("151", "- Nguyên giá", 2, new[]{"211"}, false, false),
            new("152", "- Giá trị hao mòn lũy kế (*)", 2, new[]{"214"}, false, true),
            new("160", "6. Tài sản chung không chia", 1, Array.Empty<string>(), true, false),
            new("161", "- Nguyên giá", 2, new[]{"212"}, false, false),
            new("162", "- Giá trị hao mòn lũy kế (*)", 2, new[]{"2142"}, false, true),
            // Mã 170 theo spec gồm số dư Nợ của 133/242/333. Hệ thống không tách 333 theo bên →
            // chỉ dùng 133/242; số dư Có 333 phản ánh tại Mã 330 (tránh double-count với Nợ phải trả).
            new("170", "7. Tài sản khác", 1, new[]{"133","242"}, false, false),
            new("180", "8. Dự phòng tổn thất tài sản (*)", 1, new[]{"229"}, false, true),
            new("200", "TỔNG CỘNG TÀI SẢN (200=110+120+130+140+150+160+170+180)", 0, Array.Empty<string>(), true, false),
            // NGUỒN VỐN
            new("300", "I. Nợ phải trả (300 = 310 + 320 + 330 + 340 + 350 + 360 + 370 + 380)", 0, Array.Empty<string>(), true, false),
            new("310", "1. Phải trả người bán", 1, new[]{"331"}, false, true),
            // Mã 320 = số dư Có chi tiết TK 131 (khách trả tiền trước) — không tách được theo bên → 0.
            new("320", "2. Người mua trả tiền trước", 1, Array.Empty<string>(), false, true),
            new("330", "3. Thuế và các khoản phải nộp Nhà nước", 1, new[]{"333"}, false, true),
            new("340", "4. Phải trả người lao động", 1, new[]{"334"}, false, true),
            new("350", "5. Phải trả nợ vay", 1, new[]{"341"}, false, true),
            new("360", "6. Phải trả khác", 1, new[]{"138","335","336","338","353"}, false, true),
            new("370", "7. Phải trả của hoạt động tín dụng nội bộ", 1, new[]{"332"}, false, true),
            new("380", "8. Khoản trợ cấp, hỗ trợ của Nhà nước phải hoàn lại", 1, new[]{"342"}, false, true),
            new("400", "II. Vốn chủ sở hữu (400 = 410 + 420 + 430 + 440)", 0, Array.Empty<string>(), true, false),
            new("410", "1. Vốn đầu tư của chủ sở hữu", 1, new[]{"411"}, false, true),
            new("420", "2. Lợi nhuận sau thuế chưa phân phối", 1, new[]{"421"}, false, true),
            new("430", "3. Các quỹ thuộc vốn chủ sở hữu", 1, new[]{"418"}, false, true),
            new("440", "4. Quỹ chung không chia của HTX", 1, new[]{"442"}, false, true),
            new("500", "TỔNG CỘNG NGUỒN VỐN (500=300+400)", 0, Array.Empty<string>(), true, false),
        });

    // ════════════════════════════════════════════════════════════════════════════
    // B02-HTX: Báo cáo kết quả hoạt động (VERIFIED from Phụ lục IV TT 71 — Mục I.2)
    // ════════════════════════════════════════════════════════════════════════════
    public static Tt99ReportTemplate IncomeStatementTt71 => new(
        AccountingStandard.TT71_2024, "B02-HTX",
        new List<Tt99TemplateLine>
        {
            new("01", "1. Doanh thu hoạt động sản xuất kinh doanh", 1, Array.Empty<string>(), true, false),
            new("01a", "- Doanh thu của giao dịch bên ngoài", 2, new[]{"511"}, false, false),
            new("01b", "- Doanh thu của giao dịch nội bộ", 2, new[]{"512"}, false, false),
            new("02", "2. Các khoản giảm trừ doanh thu", 1, Array.Empty<string>(), true, false),
            // 521 không tách được nội/ngoại bộ (1 TK duy nhất) → toàn bộ giảm trừ vào 02a; 02b = 0.
            new("02a", "- Giảm trừ doanh thu của giao dịch bên ngoài", 2, new[]{"521"}, false, false),
            new("02b", "- Giảm trừ doanh thu của giao dịch nội bộ", 2, Array.Empty<string>(), false, false),
            new("10", "3. Doanh thu thuần hoạt động SXKD (10 = 01 - 02)", 1, Array.Empty<string>(), true, false),
            new("10a", "- Doanh thu thuần của giao dịch bên ngoài", 2, Array.Empty<string>(), true, false),
            new("10b", "- Doanh thu thuần của giao dịch nội bộ", 2, Array.Empty<string>(), true, false),
            new("11", "4. Giá vốn hàng bán", 1, Array.Empty<string>(), true, false),
            new("11a", "- Giá vốn hàng bán của giao dịch bên ngoài", 2, new[]{"611"}, false, false),
            new("11b", "- Chi phí của giao dịch nội bộ", 2, new[]{"612"}, false, false),
            new("12", "5. Chi phí quản lý kinh doanh", 1, new[]{"642"}, false, false),
            // 12a/12b (CP QLKD phân bổ nội/ngoại) — dữ liệu không có dấu hiệu phân bổ → 0 (ghi chú tài liệu).
            new("12a", "- CP QLKD phân bổ cho giao dịch bên ngoài", 2, Array.Empty<string>(), false, false),
            new("12b", "- CP QLKD phân bổ cho giao dịch nội bộ", 2, Array.Empty<string>(), false, false),
            new("20", "6. Kết quả hoạt động SXKD (20 = 10 - 11 - 12)", 1, Array.Empty<string>(), true, false),
            new("20a", "- KQ HĐKD của giao dịch bên ngoài", 2, Array.Empty<string>(), true, false),
            new("20b", "- KQ HĐKD của giao dịch nội bộ", 2, Array.Empty<string>(), true, false),
            new("31", "7. Thu nhập khác", 1, new[]{"558"}, false, false),
            new("32", "8. Chi phí khác", 1, new[]{"658"}, false, false),
            new("40", "9. Lợi nhuận khác (40 = 31 - 32)", 1, Array.Empty<string>(), true, false),
            new("50", "10. Lợi nhuận kế toán trước thuế (50 = 20 + 40)", 1, Array.Empty<string>(), true, false),
            new("51", "11. Chi phí thuế TNDN", 1, new[]{"659"}, false, false),
            new("60", "12. Lợi nhuận sau thuế TNDN (60 = 50 - 51)", 1, Array.Empty<string>(), true, false),
        });
}
